#!/bin/sh
cd "${0%/*}" || exit            # Run from this directory
set -- -all="${0##*/}" "$@"     # Execute this instead of ./Allwmake
. "${WM_PROJECT_DIR:?}"/wmake/scripts/AllwmakeParseArguments
. "${WM_PROJECT_DIR:?}"/wmake/scripts/wmakeFunctions  # Need wmake functions

#------------------------------------------------------------------------------
# Environment
#   - FOAM_MPI_LIBBIN (optional: defaults to FOAM_LIBBIN/FOAM_MPI)

# Never need/want openmp for MPI interfaces
wmakeLibMpi -no-openmp mpi

#------------------------------------------------------------------------------
